#Application Name
spring:
  application:
    name: echo-service     # This is the name for the remote configuration file
  cloud:
    config:
      uri: http://localhost:8888  #where the config-service is running
      fail-fast: true
